// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD26US06xmWwWCllCZsyQ47JPHXj4M186A',
    appId: '1:91114233040:android:940ba17f5d26006b6252d5',
    messagingSenderId: '91114233040',
    projectId: 'whatsapp-backend-20f3e',
    storageBucket: 'whatsapp-backend-20f3e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMce_54no9RcwvZn_5IRL4MZTzIOr8XII',
    appId: '1:91114233040:ios:ce396e550e809a576252d5',
    messagingSenderId: '91114233040',
    projectId: 'whatsapp-backend-20f3e',
    storageBucket: 'whatsapp-backend-20f3e.appspot.com',
    iosBundleId: 'com.example.whatsappUi',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD26US06xmWwWCllCZsyQ47JPHXj4M186A',
    appId: '1:91114233040:web:940ba17f5d26006b6252d5',
    messagingSenderId: '91114233040',
    projectId: 'whatsapp-backend-20f3e',
    authDomain: 'whatsapp-backend-20f3e.firebaseapp.com',
    storageBucket: 'whatsapp-backend-20f3e.appspot.com',
    measurementId: 'G-ABCDEFGH1J'
  );
}
